name: ci

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        java: [ 8, 14 ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package
        run: mvn -B clean package jacoco:report

      - name: Coverage
        uses: codecov/codecov-action@v3.1.4
        with:
          file: target/site/jacoco/jacoco.xml
